Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import Blog.settings as settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('news.urls')), 
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path, include
from news import views

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path("logout/", views.user_logout, name="logout"),
    path('feedback/', views.feedback, name='feedback'),
    # path('', views.index, name='home'),
    path('', views.HomeNews.as_view(), name='home'),
    path('category/<int:category_id>/', views.NewsByCategory.as_view(), name='category'),
    path('news/<int:pk>/', views.view_news.as_view(), name='view_news'),
    path('news/add-news/', views.CreateNews.as_view(), name='add_news'),
]

news/models.py
from distutils.command.upload import upload
from django.urls import reverse
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(blank=True, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True)   

    def get_absolute_url(self):
        return reverse("view_news", kwargs={"pk": self.pk})

    def __str__(self):
        return f'({self.pk}) {self.title}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['created_at']

class Category(models.Model):
    title=models.CharField(max_length=150, db_index=True, verbose_name='Наименование категории') #  Сделали индексацию
    
    def get_absolute_url(self):
        return reverse("category", kwargs={"category_id": self.pk})

    def __str__(self):
        return f'{self.title}'
    class Meta:
        verbose_name='Категория'
        verbose_name_plural='Категории'
        ordering=['title']

news/forms.py
from cProfile import label
from django import forms
from .models import Category, News
import re
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User  
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

class ContactForm(forms.Form):
    subject = forms.CharField(label='Тема', widget=forms.TextInput(attrs={'class':'form-control'}))
    content = forms.CharField(label='Текст', widget=forms.Textarea(attrs={'class':'form-control', 'rows':5}))
    captcha = CaptchaField(label='')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', 
        widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label='Пароль', 
        widget=forms.PasswordInput(attrs={'class':'form-control'}))

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        label='Имя пользователя', 
        widget=forms.TextInput(attrs={'class':'form-control', 'autocomplete':'off'}),
        help_text='Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.'
        )
    password1 = forms.CharField(label='Пароль', 
        widget=forms.PasswordInput(attrs={'class':'form-control'}),
        help_text=''' 
        <ul> 
        <li>Пароль не должен быть слишком похож на другую вашу личную информацию.</li>
        <li>Ваш пароль должен содержать как минимум 8 символов.</li>
        <li>Пароль не должен быть слишком простым и распространенным.</li>
        <li>Пароль не может состоять только из цифр.</li>
        </ul>'''
        )
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class':'form-control'}))


    class Meta:
        model = User   
        fields = ('username', 'email', 'password1', 'password2')


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        # fields = '__all__'
        fields = ['title', 'content', 'is_published', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control' }),
            'content': forms.Textarea(attrs={'class':'form-control', 'rows': 4 }),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'category' : forms.Select(attrs={'class':'form-control' })
        }
    def clean_title(self):
        title = self.cleaned_data['title']
        if re.match('\d', title):
            raise ValidationError('Заголовок не должен начинаться с цифры!')
        return title

news/views.py
from email import message
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import login, logout
from django.core.mail import send_mail
from .models import News, Category
from .forms import NewsForm, UserRegisterForm, UserLoginForm, ContactForm
from .utils import MyMixin


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid(): 
            # news = News.objects.create(**form.cleaned_data) # Если форма не связана с моделью
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы успешно зарегистрировались')
            return redirect('login')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()
    return render(request, 'news/register.html', {'form': form, 'title': 'Регистрация'})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = UserLoginForm()
    return render(request, 'news/login.html', {'form': form, 'title': 'Вход'})

def user_logout(request):
    logout(request)
    return redirect('login')

def feedback(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid(): 
            mail = send_mail(form.cleaned_data['subject'], form.cleaned_data['content'],
            'USERNAME@f0711509.xsph.ru', ['@gmail.com'], fail_silently=True)
            if mail:
                messages.success(request, 'Письмо отправлено')
                return redirect('test')
            else:
                message.error(request, 'Ошибка отправки')
        else:
            messages.error(request, 'Ошибка валидации')
    else:
        form = ContactForm()
    return render(request, 'news/feedback.html', {'title' : 'Обратная связь', 'form':form})


# CBV - class based views
class HomeNews(MyMixin, ListView):
    model = News
    template_name = 'news/home_news_list.html'
    context_object_name = 'news'

    # extra_context = {'title': 'Main page'} # Только для статических данных
    mixin_prob = 'Probe!'
    paginate_by = 5


    def get_context_data(self, *, object_list=None, **kwargs) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_upper('Все статьи')
        context['mixin_prob'] = self.get_prob()
        return context
    
    def get_queryset(self):
        return News.objects.filter(is_published = True).select_related('category')

# def index(request: HttpRequest):
#     news = News.objects.all()
#     context = {'news': news, 
#     'title': 'Список записей'
#     }
#     return render(request,  'news/index.html', context)

class NewsByCategory(MyMixin, ListView):
    model = News
    template_name = 'news/category_list.html'
    context_object_name = 'news_cat'
    allow_empty = False
    def get_context_data(self, *, object_list=None, **kwargs) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категория "' + self.get_upper(Category.objects.get(pk=self.kwargs['category_id'])) + '"'
        context['category'] = context['title']
        return context
    def get_queryset(self):
        return News.objects.filter(is_published = True, category_id=self.kwargs['category_id']).select_related('category')
# def get_category(request: HttpRequest, category_id: int):
#     news_cat = News.objects.filter(category_id=category_id)
#     category = Category.objects.get(pk=category_id)
#     context={'news_cat': news_cat,
#     'category': category,
#     'title': category.title}
#     return render(request, template_name='news/category.html', context=context)

class view_news(DetailView):
    model = News
    # pk_url_kwarg = 'news_id'
    

# def view_news(request: HttpRequest, news_id: int):
#     news_item = get_object_or_404(News, pk=news_id)
#     context = {
#         'title': news_item.title,
#         'news_item': news_item
#         }
#     return render(request, template_name='news/view_news.html', context=context)

class CreateNews(LoginRequiredMixin, CreateView):
    form_class = NewsForm
    template_name = 'news/add-news.html'
    success_url =  reverse_lazy('home')
    login_url = '/admin/'

    def get_context_data(self, *, object_list=None, **kwargs) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить статью'
        return context


# def add_news(request: HttpRequest):
#     if request.method == 'POST':
#         form = NewsForm(request.POST)
#         if form.is_valid():
#             # news = News.objects.create(**form.cleaned_data) # Если форма не связана с моделью
#             news = form.save()
#             return redirect(news)
#     else:
#         form = NewsForm()
#     context = {'title': 'Добавление новости',
#     'form': form}
#     return render(request, template_name='news/add-news.html', context=context)

news/templates/news/add-news.html
{% extends 'base.html' %} 

{% block title %}
  {{title}} :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}

    <form action="{% url 'add_news' %}" method='POST'>
            {% csrf_token %}
            {{form.as_p}}
    {% comment "Standart form" %}
    {{ form.none_field.errors}}
    <div class="mb-3">
        {{form.title}}
        <div class='invalid-feedback'>
            {{form.title.errors}}
        </div>
    </div>
    <div class="mb-3">
        <label for="{{form.content.id_for_label}}" class="form-label">Content</label>
        {{form.content}}
        <div class='invalid-feedback'>
            {{form.content.errors}}
        </div>
    </div>
    <div class="mb-3">
        <label for="{{form.is_published.id_for_label}}" class="form-label">Publication</label>
        {{form.is_published}}
        <div class='invalid-feedback'>
            {{form.is_published.errors}}
        </div>
    </div>
    <div class="mb-3">
        <label for="{{form.category.id_for_label}}" class="form-label">Category</label>
        {{form.category}}
        <div class='invalid-feedback'>
            {{form.category.errors}}
        </div>
    </div>
    {% endcomment %}

    {% comment "Standart form" %}
    {%for field in form %}
        <div class='mb-3'>
            {{field.label_tag}}
            {{field}}
            <div class='invalid-feedback'>
                {{field.category.errors}}
            </div>
        </div>
    {%endfor%}
    {% endcomment %}
        <button type='submit' class='btn btn-primary btn-block'> Add new </button>
    </form>
{% endblock content %}

news/templates/news/category.html
{% extends 'base.html' %} 

{% block title %}
  {{title}} :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
{% for i in news_cat %}
<div class="card mb-3">
  <div class="card-header">Категория: {{i.category}}</div>
  <div class="card-body">
    <div class="media">
      <div class="media-body">
        {% if i.photo %}
        <img width="500" height="300" src="{{i.photo.url}}" alt="" />
        {%else%}
        <img src="https://picsum.photos/seed/picsum/200/300" />
        {% endif %}
      </div>
      <br>
      <h4 class="card-title {% cycle 'text-danger' 'text-success' %}">
        {{i.title}}
      </h4>
      <p class="card-text">{{i.content}}</p>
      <a href="{{i.get_absolute_url}}" class="btn btn-primary">Read more...</a>
    </div>
  </div>
  <div class="card-footer text-muted">{{i.created_at |timesince}}</div>
</div>
{% endfor %}
{% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
      integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

news/templates/news/category_list.html
{% extends 'base.html' %} 

{% block title %}
  {{title}} :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
{% for i in news_cat %}
<div class="card mb-3">
  <div class="card-header">Категория: {{i.category}}</div>
  <div class="card-body">
    <div class="media">
      <div class="media-body">
        {% if i.photo %}
        <img width="500" height="300" src="{{i.photo.url}}" alt="" />
        {%else%}
        <img src="https://picsum.photos/seed/picsum/200/300" />
        {% endif %}
      </div>
      <br>
      <h4 class="card-title {% cycle 'text-danger' 'text-success' %}">
        {{i.title}}
      </h4>
      <p class="card-text">{{i.content}}</p>
      <a href="{{i.get_absolute_url}}" class="btn btn-primary">Read more...</a>
    </div>
  </div>
  <div class="card-footer text-muted">{{i.created_at |timesince}}</div>
</div>
{% endfor %}
{% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
      integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

news/templates/news/feedback.html
{% extends 'base.html' %} 

{% block title %}
  {{title}} :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
<form method='post'>
  {% csrf_token %}
  {{form.as_p}}
  <button type='submit' class='btn btn-primary btn-block'> Send </button>
</form>
{% endblock content %}

news/templates/news/home_news_list.html
{% extends 'base.html' %} 

{% block title %}
  {{title}} :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
{% for i in news %}
<div class="card mb-3">
  <div class="card-header">Категория: <a href='{{ i.category.get_absolute_url }}'>{{i.category}}</a></div>
  <div class="card-body">
    <div class="media">
      <div class="media-body">
        {% if i.photo %}
        <img width="500" height="300" src="{{i.photo.url}}" alt="" />
        {%else%}
        <img src="https://picsum.photos/seed/picsum/200/300" />
        {% endif %}
      </div>
      <br>
      <h4 class="card-title {% cycle 'text-danger' 'text-success' %}">
        {{i.title}}
      </h4>
      <p class="card-text">{{i.content}}</p>
      <a href="{{i.get_absolute_url}}" class="btn btn-primary">Read more...</a>
    </div>
  </div>
  <div class="card-footer text-muted">{{i.created_at |timesince}}</div>
</div>
{% endfor %}
{% endblock content %}

news/templates/news/list_categories.html
<div class="list-group">
    {% for j in categories %}
    <a
      {% comment %} href="{% url 'category' j.pk %}" {% endcomment %}
      href="{{j.get_absolute_url}}"
      class="list-group-item list-group-item-action"
    >
    {% comment "Вычисления на странице" %}
    {{j.title}} <span class="badge bg-primary rounded-pill">{{j.news_set.count}}</span>
    {% endcomment %}
      {{j.title}} <span class="badge bg-primary rounded-pill">{{j.cnt}}</span>
    </a>
    {% endfor %}
</div>

news/templates/news/login.html
{% extends 'base.html' %} 

{% block title %}
  Вход :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
    <form method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit' class='btn btn-primary btn-block'> Войти </button>
    </form> 
{% endblock content %}

news/templates/news/news_detail.html
{% extends 'base.html' %} 

{% block title %}
  {{title}} :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
<div class="card mb-3">
  <div class="card-header">Категория: <a href='{{ object.category.get_absolute_url }}'>{{object.category}}</a></div>
  <div class="card-body">
    <h4 class="card-title">{{object.title}}</h4>
    <div class="media">
      <div class="media-body">
        {% if object.photo %}
        <img width="500" height="300" src="{{object.photo.url}}" alt="" />
        {%else%}
        <img src="https://picsum.photos/seed/picsum/200/300" />
        {% endif %}
      </div>
      <h5 class="card-title {% cycle 'text-danger' 'text-success' %}">
        {{i.title}}
      </h5>
      <p class="card-text">{{object.content}}</p>
    </div>
  </div>
  <div class="card-footer text-muted">{{object.created_at |timesince}}</div>
</div>
{% endblock content %}

news/templates/news/register.html
{% extends 'base.html' %} 

{% block title %}
  Регистрация :: {{block.super}}
{% endblock title %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock sidebar %} 

{% block content %}
    <form action="{% url 'register' %}" method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit' class='btn btn-primary btn-block'> Зарегестрироваться </button> 
    </form>
{% endblock content %}